In [1]:
import numpy as np
import pandas as pd
from scipy import stats
import statsmodels.api as sm


In [2]:
animal_ls = ['cat', 'dog', 'fish', 'bird', ' moose', 'snake', ' axlotl']

In [4]:
#acess cat
animal_ls[0]

'cat'

In [6]:
animal_ls[2:5]
animal_ls [2:-2]
#access fish to moose

['fish', 'bird', ' moose']

In [8]:
#want all 
animal_ls[:7]
animal_ls[:]

['cat', 'dog', 'fish', 'bird', ' moose', 'snake', ' axlotl']

In [11]:
#list comprehemsion if wnat to do something to eahc of the things in the list
#another list blank is animal 
result_ls = []
for animal in animal_ls:
    result_ls.append (animal + "is an animal")

In [12]:
result_ls

['catis an animal',
 'dogis an animal',
 'fishis an animal',
 'birdis an animal',
 ' mooseis an animal',
 'snakeis an animal',
 ' axlotlis an animal']

In [15]:
#list comprehension 
result_ls = [animal + "is an animal" for animal in animal_ls]

In [16]:
result_ls

['catis an animal',
 'dogis an animal',
 'fishis an animal',
 'birdis an animal',
 ' mooseis an animal',
 'snakeis an animal',
 ' axlotlis an animal']

In [17]:
a = np.array ([[1,2,3,4],
               [5,6,7,8]])

In [ ]:
a.shape
#2 rows and 4 columns

(2, 4)

In [ ]:
a.dtype
#only contains intg. 

dtype('int64')

In [21]:
#array one dimensional 
b=np.array([7,8,9,10,11])

In [22]:
b

array([ 7,  8,  9, 10, 11])

In [23]:
b.shape

(5,)

In [24]:
#convert from one type to another 
b.astype(float)

array([ 7.,  8.,  9., 10., 11.])

In [25]:
b.astype (str)

array(['7', '8', '9', '10', '11'], dtype='<U21')

In [26]:
b

array([ 7,  8,  9, 10, 11])

In [27]:
#access 8
b [1]

np.int64(8)

In [ ]:
b[1:]
#to access till the end

array([ 8,  9, 10, 11])

In [ ]:
#2 dimensional aaray to get the first row  
a[0, :]

array([1, 2, 3, 4])

In [ ]:
#to get a column from a see below
a[:,2]

array([3, 7])

In [30]:
a 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
a= np.arange(1000)
#arange will give all numbers from 0 to 999 1000 numbers

In [35]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [36]:
a.shape

(1000,)

In [37]:
a.dtype

dtype('int64')

In [ ]:
b=np.linspace (0,1,10001)
#evenly spaced number from on evalue to another 
# with arange we specify 1000 brough us to 1000 vs linespace includes the 2 ends and I wanted 10001 numbers

In [41]:
b

array([0.000e+00, 1.000e-04, 2.000e-04, ..., 9.998e-01, 9.999e-01,
       1.000e+00])

In [44]:
#create array populated by random numbers 10 by 4 array of number
c=np.random.standard_normal((10,4))

In [45]:
c


array([[ 0.5484724 ,  0.60555047,  2.63087715,  0.58716154],
       [ 0.71814423,  1.16535185, -0.14130947,  0.38661475],
       [ 0.25311313, -0.37871742, -1.67074796, -1.12007192],
       [-0.06615186,  0.76421429, -1.23823117,  0.4192356 ],
       [ 0.3691284 ,  0.33564897, -0.07910505,  0.6869957 ],
       [ 1.51613294,  0.83700951,  0.26740285,  0.71463988],
       [-0.83716458,  2.14872215,  0.85130988,  0.06991122],
       [-0.44887409, -0.19770987,  0.41450932,  0.74518141],
       [-0.74846609,  1.44432447,  0.47107329,  0.44153057],
       [ 0.47365821,  0.32789334,  0.34233205,  0.97193328]])

In [46]:
c.var()

np.float64(0.6748226890374278)

In [47]:
d= np.random.standard_normal((1000,))
#the in between putple is shape

In [48]:
d.mean()

np.float64(-0.005753528202475291)

In [53]:
a=np.random.choice([1,2,3],(7,3))
b=np.arange(7)
#rnadom array choses from a list of pos,sible values the shape here is 7 by 3 

In [54]:
a

array([[2, 2, 2],
       [1, 3, 3],
       [3, 1, 3],
       [3, 3, 1],
       [3, 1, 2],
       [1, 2, 2],
       [3, 2, 3]])

In [55]:
b

array([0, 1, 2, 3, 4, 5, 6])

In [56]:
a+a

array([[4, 4, 4],
       [2, 6, 6],
       [6, 2, 6],
       [6, 6, 2],
       [6, 2, 4],
       [2, 4, 4],
       [6, 4, 6]])

In [ ]:
a+b
#issue, these arrays cannot be added because of incompatible shape a is 2 dimensional vs b 2 dimesntional array

ValueError: operands could not be broadcast together with shapes (7,3) (7,) 

In [ ]:
#to get B added to each column , reshape b to 2 dimenstional array 7 by 1. Math between 2 arrays should have same shape
b = b.reshape((7,1))


In [59]:
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [60]:
#b added to each column of a 
a+b

array([[2, 2, 2],
       [2, 4, 4],
       [5, 3, 5],
       [6, 6, 4],
       [7, 5, 6],
       [6, 7, 7],
       [9, 8, 9]])

In [ ]:
#numpy "broadcast" arithmetic between arrays if they have compatible shapes

In [61]:
##Pandas

In [68]:
toy_df = pd.DataFrame(data =[['cat',1],
                              ['dog', 3],
                              ['fish', 4]],
                      columns = ["animal", "weight"],
                      index = ['a','b', 'c'])
#df is data frame 3 rows 

In [69]:
toy_df

animal  weight
a    cat       1
b    dog       3
c   fish       4

In [ ]:
#in nonpay array all should be strings or all should be numbers vs here we have both 

In [70]:
toy_df.columns

Index(['animal', 'weight'], dtype='object')

In [71]:
toy_df.index

Index(['a', 'b', 'c'], dtype='object')

In [72]:
toy_df. info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, a to c
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   animal  3 non-null      object
 1   weight  3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes


In [73]:
#if animal columns interest me
toy_df ['animal']

a     cat
b     dog
c    fish
Name: animal, dtype: object

In [76]:
toy_df["age"]= [5.0,3.0,1.0]

In [77]:
toy_df

animal  weight  age
a    cat       1  5.0
b    dog       3  3.0
c   fish       4  1.0

In [79]:
toy_df["new column"]= [5,6,None]

In [80]:
toy_df

animal  weight  age  new column
a    cat       1  5.0         5.0
b    dog       3  3.0         6.0
c   fish       4  1.0         NaN

In [82]:
toy_df.loc[['b', 'c'], ['weight', 'age']]
#gave me rows b and c and columns weight and age when used.loc

weight  age
b       3  3.0
c       4  1.0

In [ ]:
toy_df["animal"] == "dog"
#note it is double =; the only place where animal is equal to dog is row b 

a    False
b     True
c    False
Name: animal, dtype: bool

In [84]:
toy_df.loc[toy_df["animal"]== "dog", :]

animal  weight  age  new column
b    dog       3  3.0         6.0

In [86]:
toy_df.loc [(toy_df ["animal"]== "dog") | (toy_df["animal"]=="cat"),]

animal  weight  age  new column
a    cat       1  5.0         5.0
b    dog       3  3.0         6.0

In [88]:
iris_df= pd.read_csv("iris_missing_values.csv")

In [89]:
iris_df

Unnamed: 0  sepal length (cm)  ...  petal width (cm)       type
0      flower_0                5.1  ...               0.2     setosa
1      flower_1                4.9  ...               0.2     setosa
2      flower_2                4.7  ...               0.2     setosa
3      flower_3                4.6  ...               0.2     setosa
4      flower_4                5.0  ...               0.2     setosa
..          ...                ...  ...               ...        ...
145  flower_145                6.7  ...               2.3  virginica
146  flower_146                6.3  ...               1.9  virginica
147  flower_147                6.5  ...               2.0  virginica
148  flower_148                6.2  ...               2.3  virginica
149  flower_149                5.9  ...               1.8        NaN

[150 rows x 6 columns]

In [90]:
iris_df.index

RangeIndex(start=0, stop=150, step=1)

In [91]:
#to use unique column as index
iris_df.set_index("Unnamed: 0")

sepal length (cm)  sepal width (cm)  ...  petal width (cm)       type
Unnamed: 0                                       ...                             
flower_0                  5.1               3.5  ...               0.2     setosa
flower_1                  4.9               3.0  ...               0.2     setosa
flower_2                  4.7               3.2  ...               0.2     setosa
flower_3                  4.6               3.1  ...               0.2     setosa
flower_4                  5.0               3.6  ...               0.2     setosa
...                       ...               ...  ...               ...        ...
flower_145                6.7               3.0  ...               2.3  virginica
flower_146                6.3               2.5  ...               1.9  virginica
flower_147                6.5               3.0  ...               2.0  virginica
flower_148                6.2               3.4  ...               2.3  virginica
flower_149                5.9               3.0  ...               1.8        NaN

[150 rows x 5 columns]

In [93]:
#so not to copy and give the new data frame but change on the same data fram 
iris_df.set_index("Unnamed: 0", inplace=True)

In [94]:
iris_df

sepal length (cm)  sepal width (cm)  ...  petal width (cm)       type
Unnamed: 0                                       ...                             
flower_0                  5.1               3.5  ...               0.2     setosa
flower_1                  4.9               3.0  ...               0.2     setosa
flower_2                  4.7               3.2  ...               0.2     setosa
flower_3                  4.6               3.1  ...               0.2     setosa
flower_4                  5.0               3.6  ...               0.2     setosa
...                       ...               ...  ...               ...        ...
flower_145                6.7               3.0  ...               2.3  virginica
flower_146                6.3               2.5  ...               1.9  virginica
flower_147                6.5               3.0  ...               2.0  virginica
flower_148                6.2               3.4  ...               2.3  virginica
flower_149                5.9               3.0  ...               1.8        NaN

[150 rows x 5 columns]

In [ ]:
iris_df['type'].value_counts()
#values counts null values unless - next one

type
setosa        46
versicolor    45
virginica     44
Name: count, dtype: int64

In [103]:
iris_df['type'].value_counts(dropna=false)

NameError: name 'false' is not defined

In [118]:
iris_df=pd.read_csv("iris_missing_values.csv", index_col=0)

In [119]:
iris_df

sepal length (cm)  sepal width (cm)  ...  petal width (cm)       type
flower_0                  5.1               3.5  ...               0.2     setosa
flower_1                  4.9               3.0  ...               0.2     setosa
flower_2                  4.7               3.2  ...               0.2     setosa
flower_3                  4.6               3.1  ...               0.2     setosa
flower_4                  5.0               3.6  ...               0.2     setosa
...                       ...               ...  ...               ...        ...
flower_145                6.7               3.0  ...               2.3  virginica
flower_146                6.3               2.5  ...               1.9  virginica
flower_147                6.5               3.0  ...               2.0  virginica
flower_148                6.2               3.4  ...               2.3  virginica
flower_149                5.9               3.0  ...               1.8        NaN

[150 rows x 5 columns]

In [131]:
virginica_df= iris_df.loc[iris_df["type"]=="virginica", :]

In [120]:
setosa_df = iris_df.loc[iris_df["type"]=="setosa", :]

In [121]:
setosa_df
#gave me all setosa_df, this is a view of data frame

sepal length (cm)  sepal width (cm)  ...  petal width (cm)    type
flower_0                 5.1               3.5  ...               0.2  setosa
flower_1                 4.9               3.0  ...               0.2  setosa
flower_2                 4.7               3.2  ...               0.2  setosa
flower_3                 4.6               3.1  ...               0.2  setosa
flower_4                 5.0               3.6  ...               0.2  setosa
flower_5                 5.4               3.9  ...               0.4  setosa
flower_6                 4.6               3.4  ...               0.3  setosa
flower_7                 5.0               3.4  ...               0.2  setosa
flower_8                 4.4               2.9  ...               0.2  setosa
flower_9                 4.9               3.1  ...               0.1  setosa
flower_10                5.4               3.7  ...               0.2  setosa
flower_11                4.8               3.4  ...               0.2  setosa
flower_13                4.3               3.0  ...               0.1  setosa
flower_14                5.8               4.0  ...               0.2  setosa
flower_15                5.7               4.4  ...               0.4  setosa
flower_16                5.4               3.9  ...               0.4  setosa
flower_17                5.1               3.5  ...               0.3  setosa
flower_18                5.7               3.8  ...               0.3  setosa
flower_20                5.4               3.4  ...               0.2  setosa
flower_21                5.1               3.7  ...               0.4  setosa
flower_22                4.6               3.6  ...               0.2  setosa
flower_23                5.1               3.3  ...               0.5  setosa
flower_25                5.0               3.0  ...               0.2  setosa
flower_26                5.0               3.4  ...               0.4  setosa
flower_27                5.2               3.5  ...               0.2  setosa
flower_28                5.2               3.4  ...               0.2  setosa
flower_29                4.7               3.2  ...               0.2  setosa
flower_30                4.8               3.1  ...               0.2  setosa
flower_31                5.4               3.4  ...               0.4  setosa
flower_32                5.2               4.1  ...               0.1  setosa
flower_33                5.5               4.2  ...               0.2  setosa
flower_34                4.9               3.1  ...               0.2  setosa
flower_35                5.0               3.2  ...               0.2  setosa
flower_36                5.5               3.5  ...               0.2  setosa
flower_37                4.9               3.6  ...               0.1  setosa
flower_38                4.4               3.0  ...               0.2  setosa
flower_39                5.1               3.4  ...               0.2  setosa
flower_40                5.0               3.5  ...               0.3  setosa
flower_41                4.5               2.3  ...               0.3  setosa
flower_43                5.0               3.5  ...               0.6  setosa
flower_44                5.1               3.8  ...               0.4  setosa
flower_45                4.8               3.0  ...               0.3  setosa
flower_46                5.1               3.8  ...               0.2  setosa
flower_47                4.6               3.2  ...               0.2  setosa
flower_48                5.3               3.7  ...               0.2  setosa
flower_49                5.0               3.3  ...               0.2  setosa

[46 rows x 5 columns]

In [122]:
type_dfs = []
for type in ["setosa", "versicolar", 'verginia']:
    type_dfs.append (iris_df.loc[iris_df['type']==type, :])

In [123]:
type_dfs

[           sepal length (cm)  sepal width (cm)  ...  petal width (cm)    type
 flower_0                 5.1               3.5  ...               0.2  setosa
 flower_1                 4.9               3.0  ...               0.2  setosa
 flower_2                 4.7               3.2  ...               0.2  setosa
 flower_3                 4.6               3.1  ...               0.2  setosa
 flower_4                 5.0               3.6  ...               0.2  setosa
 flower_5                 5.4               3.9  ...               0.4  setosa
 flower_6                 4.6               3.4  ...               0.3  setosa
 flower_7                 5.0               3.4  ...               0.2  setosa
 flower_8                 4.4               2.9  ...               0.2  setosa
 flower_9                 4.9               3.1  ...               0.1  setosa
 flower_10                5.4               3.7  ...               0.2  setosa
 flower_11                4.8               3.4  ...

In [124]:
iris_df.iloc[:20, :3]
#select first 20 rows and firs 3 rows

sepal length (cm)  sepal width (cm)  petal length (cm)
flower_0                 5.1               3.5                1.4
flower_1                 4.9               3.0                1.4
flower_2                 4.7               3.2                1.3
flower_3                 4.6               3.1                1.5
flower_4                 5.0               3.6                1.4
flower_5                 5.4               3.9                1.7
flower_6                 4.6               3.4                1.4
flower_7                 5.0               3.4                1.5
flower_8                 4.4               2.9                1.4
flower_9                 4.9               3.1                1.5
flower_10                5.4               3.7                1.5
flower_11                4.8               3.4                1.6
flower_12                4.8               3.0                1.4
flower_13                4.3               3.0                1.1
flower_14                5.8               4.0                1.2
flower_15                5.7               4.4                1.5
flower_16                5.4               3.9                1.3
flower_17                5.1               3.5                1.4
flower_18                5.7               3.8                1.7
flower_19                5.1               3.8                1.5

In [125]:
iris_df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'type'],
      dtype='object')

In [127]:
#math with data frame, create new columns from old columns
iris_df["sum_lenghts"]= iris_df["sepal length (cm)"]+iris_df["petal length (cm)"]

In [128]:
iris_df

sepal length (cm)  sepal width (cm)  ...       type  sum_lenghts
flower_0                  5.1               3.5  ...     setosa          6.5
flower_1                  4.9               3.0  ...     setosa          6.3
flower_2                  4.7               3.2  ...     setosa          6.0
flower_3                  4.6               3.1  ...     setosa          6.1
flower_4                  5.0               3.6  ...     setosa          6.4
...                       ...               ...  ...        ...          ...
flower_145                6.7               3.0  ...  virginica         11.9
flower_146                6.3               2.5  ...  virginica         11.3
flower_147                6.5               3.0  ...  virginica         11.7
flower_148                6.2               3.4  ...  virginica         11.6
flower_149                5.9               3.0  ...        NaN         11.0

[150 rows x 6 columns]

##statistics with scipy and statsmodels

In [129]:
setosa_df

sepal length (cm)  sepal width (cm)  ...  petal width (cm)    type
flower_0                 5.1               3.5  ...               0.2  setosa
flower_1                 4.9               3.0  ...               0.2  setosa
flower_2                 4.7               3.2  ...               0.2  setosa
flower_3                 4.6               3.1  ...               0.2  setosa
flower_4                 5.0               3.6  ...               0.2  setosa
flower_5                 5.4               3.9  ...               0.4  setosa
flower_6                 4.6               3.4  ...               0.3  setosa
flower_7                 5.0               3.4  ...               0.2  setosa
flower_8                 4.4               2.9  ...               0.2  setosa
flower_9                 4.9               3.1  ...               0.1  setosa
flower_10                5.4               3.7  ...               0.2  setosa
flower_11                4.8               3.4  ...               0.2  setosa
flower_13                4.3               3.0  ...               0.1  setosa
flower_14                5.8               4.0  ...               0.2  setosa
flower_15                5.7               4.4  ...               0.4  setosa
flower_16                5.4               3.9  ...               0.4  setosa
flower_17                5.1               3.5  ...               0.3  setosa
flower_18                5.7               3.8  ...               0.3  setosa
flower_20                5.4               3.4  ...               0.2  setosa
flower_21                5.1               3.7  ...               0.4  setosa
flower_22                4.6               3.6  ...               0.2  setosa
flower_23                5.1               3.3  ...               0.5  setosa
flower_25                5.0               3.0  ...               0.2  setosa
flower_26                5.0               3.4  ...               0.4  setosa
flower_27                5.2               3.5  ...               0.2  setosa
flower_28                5.2               3.4  ...               0.2  setosa
flower_29                4.7               3.2  ...               0.2  setosa
flower_30                4.8               3.1  ...               0.2  setosa
flower_31                5.4               3.4  ...               0.4  setosa
flower_32                5.2               4.1  ...               0.1  setosa
flower_33                5.5               4.2  ...               0.2  setosa
flower_34                4.9               3.1  ...               0.2  setosa
flower_35                5.0               3.2  ...               0.2  setosa
flower_36                5.5               3.5  ...               0.2  setosa
flower_37                4.9               3.6  ...               0.1  setosa
flower_38                4.4               3.0  ...               0.2  setosa
flower_39                5.1               3.4  ...               0.2  setosa
flower_40                5.0               3.5  ...               0.3  setosa
flower_41                4.5               2.3  ...               0.3  setosa
flower_43                5.0               3.5  ...               0.6  setosa
flower_44                5.1               3.8  ...               0.4  setosa
flower_45                4.8               3.0  ...               0.3  setosa
flower_46                5.1               3.8  ...               0.2  setosa
flower_47                4.6               3.2  ...               0.2  setosa
flower_48                5.3               3.7  ...               0.2  setosa
flower_49                5.0               3.3  ...               0.2  setosa

[46 rows x 5 columns]

In [132]:
virginica_df


sepal length (cm)  sepal width (cm)  ...       type  sum_lenghts
flower_100                6.3               3.3  ...  virginica         12.3
flower_101                5.8               2.7  ...  virginica         10.9
flower_102                7.1               3.0  ...  virginica         13.0
flower_103                6.3               2.9  ...  virginica         11.9
flower_104                6.5               3.0  ...  virginica         12.3
flower_105                7.6               3.0  ...  virginica         14.2
flower_106                4.9               2.5  ...  virginica          9.4
flower_108                6.7               2.5  ...  virginica         12.5
flower_109                7.2               3.6  ...  virginica         13.3
flower_110                6.5               3.2  ...  virginica         11.6
flower_111                6.4               2.7  ...  virginica         11.7
flower_112                6.8               3.0  ...  virginica         12.3
flower_113                5.7               2.5  ...  virginica         10.7
flower_114                5.8               2.8  ...  virginica         10.9
flower_115                6.4               3.2  ...  virginica         11.7
flower_116                6.5               3.0  ...  virginica         12.0
flower_117                7.7               3.8  ...  virginica         14.4
flower_119                6.0               2.2  ...  virginica         11.0
flower_120                6.9               3.2  ...  virginica         12.6
flower_121                5.6               2.8  ...  virginica         10.5
flower_122                7.7               2.8  ...  virginica         14.4
flower_124                6.7               3.3  ...  virginica         12.4
flower_125                7.2               3.2  ...  virginica         13.2
flower_126                6.2               2.8  ...  virginica         11.0
flower_127                6.1               3.0  ...  virginica         11.0
flower_128                6.4               2.8  ...  virginica         12.0
flower_129                7.2               3.0  ...  virginica         13.0
flower_130                7.4               2.8  ...  virginica         13.5
flower_131                7.9               3.8  ...  virginica         14.3
flower_132                6.4               2.8  ...  virginica         12.0
flower_133                6.3               2.8  ...  virginica         11.4
flower_136                6.3               3.4  ...  virginica         11.9
flower_137                6.4               3.1  ...  virginica         11.9
flower_138                6.0               3.0  ...  virginica         10.8
flower_139                6.9               3.1  ...  virginica         12.3
flower_140                6.7               3.1  ...  virginica         12.3
flower_141                6.9               3.1  ...  virginica         12.0
flower_142                5.8               2.7  ...  virginica         10.9
flower_143                6.8               3.2  ...  virginica         12.7
flower_144                6.7               3.3  ...  virginica         12.4
flower_145                6.7               3.0  ...  virginica         11.9
flower_146                6.3               2.5  ...  virginica         11.3
flower_147                6.5               3.0  ...  virginica         11.7
flower_148                6.2               3.4  ...  virginica         11.6

[44 rows x 6 columns]

In [138]:

virginica_df

sepal length (cm)  sepal width (cm)  ...       type  sum_lenghts
flower_100                6.3               3.3  ...  virginica         12.3
flower_101                5.8               2.7  ...  virginica         10.9
flower_102                7.1               3.0  ...  virginica         13.0
flower_103                6.3               2.9  ...  virginica         11.9
flower_104                6.5               3.0  ...  virginica         12.3
flower_105                7.6               3.0  ...  virginica         14.2
flower_106                4.9               2.5  ...  virginica          9.4
flower_108                6.7               2.5  ...  virginica         12.5
flower_109                7.2               3.6  ...  virginica         13.3
flower_110                6.5               3.2  ...  virginica         11.6
flower_111                6.4               2.7  ...  virginica         11.7
flower_112                6.8               3.0  ...  virginica         12.3
flower_113                5.7               2.5  ...  virginica         10.7
flower_114                5.8               2.8  ...  virginica         10.9
flower_115                6.4               3.2  ...  virginica         11.7
flower_116                6.5               3.0  ...  virginica         12.0
flower_117                7.7               3.8  ...  virginica         14.4
flower_119                6.0               2.2  ...  virginica         11.0
flower_120                6.9               3.2  ...  virginica         12.6
flower_121                5.6               2.8  ...  virginica         10.5
flower_122                7.7               2.8  ...  virginica         14.4
flower_124                6.7               3.3  ...  virginica         12.4
flower_125                7.2               3.2  ...  virginica         13.2
flower_126                6.2               2.8  ...  virginica         11.0
flower_127                6.1               3.0  ...  virginica         11.0
flower_128                6.4               2.8  ...  virginica         12.0
flower_129                7.2               3.0  ...  virginica         13.0
flower_130                7.4               2.8  ...  virginica         13.5
flower_131                7.9               3.8  ...  virginica         14.3
flower_132                6.4               2.8  ...  virginica         12.0
flower_133                6.3               2.8  ...  virginica         11.4
flower_136                6.3               3.4  ...  virginica         11.9
flower_137                6.4               3.1  ...  virginica         11.9
flower_138                6.0               3.0  ...  virginica         10.8
flower_139                6.9               3.1  ...  virginica         12.3
flower_140                6.7               3.1  ...  virginica         12.3
flower_141                6.9               3.1  ...  virginica         12.0
flower_142                5.8               2.7  ...  virginica         10.9
flower_143                6.8               3.2  ...  virginica         12.7
flower_144                6.7               3.3  ...  virginica         12.4
flower_145                6.7               3.0  ...  virginica         11.9
flower_146                6.3               2.5  ...  virginica         11.3
flower_147                6.5               3.0  ...  virginica         11.7
flower_148                6.2               3.4  ...  virginica         11.6

[44 rows x 6 columns]

In [140]:
ttest_result=stats.ttest_ind(setosa_df["sepal length (cm)"],
                             virginica_df["sepal length (cm)"],
                             equal_var=False)

In [141]:
ttest_result

TtestResult(statistic=np.float64(-14.468170059962942), pvalue=np.float64(1.7606944675930888e-22), df=np.float64(68.2858924413873))

In [142]:
stats.false_discovery_control((0.01, 0.04,0.3,0.4,0.3))

array([0.05 , 0.1  , 0.375, 0.4  , 0.375])

In [147]:
setosa_df

sepal length (cm)  sepal width (cm)  ...  petal width (cm)    type
flower_0                 5.1               3.5  ...               0.2  setosa
flower_1                 4.9               3.0  ...               0.2  setosa
flower_2                 4.7               3.2  ...               0.2  setosa
flower_3                 4.6               3.1  ...               0.2  setosa
flower_4                 5.0               3.6  ...               0.2  setosa
flower_5                 5.4               3.9  ...               0.4  setosa
flower_6                 4.6               3.4  ...               0.3  setosa
flower_7                 5.0               3.4  ...               0.2  setosa
flower_8                 4.4               2.9  ...               0.2  setosa
flower_9                 4.9               3.1  ...               0.1  setosa
flower_10                5.4               3.7  ...               0.2  setosa
flower_11                4.8               3.4  ...               0.2  setosa
flower_13                4.3               3.0  ...               0.1  setosa
flower_14                5.8               4.0  ...               0.2  setosa
flower_15                5.7               4.4  ...               0.4  setosa
flower_16                5.4               3.9  ...               0.4  setosa
flower_17                5.1               3.5  ...               0.3  setosa
flower_18                5.7               3.8  ...               0.3  setosa
flower_20                5.4               3.4  ...               0.2  setosa
flower_21                5.1               3.7  ...               0.4  setosa
flower_22                4.6               3.6  ...               0.2  setosa
flower_23                5.1               3.3  ...               0.5  setosa
flower_25                5.0               3.0  ...               0.2  setosa
flower_26                5.0               3.4  ...               0.4  setosa
flower_27                5.2               3.5  ...               0.2  setosa
flower_28                5.2               3.4  ...               0.2  setosa
flower_29                4.7               3.2  ...               0.2  setosa
flower_30                4.8               3.1  ...               0.2  setosa
flower_31                5.4               3.4  ...               0.4  setosa
flower_32                5.2               4.1  ...               0.1  setosa
flower_33                5.5               4.2  ...               0.2  setosa
flower_34                4.9               3.1  ...               0.2  setosa
flower_35                5.0               3.2  ...               0.2  setosa
flower_36                5.5               3.5  ...               0.2  setosa
flower_37                4.9               3.6  ...               0.1  setosa
flower_38                4.4               3.0  ...               0.2  setosa
flower_39                5.1               3.4  ...               0.2  setosa
flower_40                5.0               3.5  ...               0.3  setosa
flower_41                4.5               2.3  ...               0.3  setosa
flower_43                5.0               3.5  ...               0.6  setosa
flower_44                5.1               3.8  ...               0.4  setosa
flower_45                4.8               3.0  ...               0.3  setosa
flower_46                5.1               3.8  ...               0.2  setosa
flower_47                4.6               3.2  ...               0.2  setosa
flower_48                5.3               3.7  ...               0.2  setosa
flower_49                5.0               3.3  ...               0.2  setosa

[46 rows x 5 columns]

In [151]:
stats.pearsonr(setosa_df["sepal length (cm)"], setosa_df['sepal width (cm)'])


PearsonRResult(statistic=np.float64(0.7504786420491917), pvalue=np.float64(1.910641490623207e-09))

In [ ]:
from matplotlib import pyplot as plt
plt.scatter(setosa_df ['petal lenght (cm)'],
             setosa_df ['petal width (cm)'])

ModuleNotFoundError: No module named 'metplotlib'